name: UltimateDuels
version: '${project.version}'
main: me.mistakenn.ultimateduels.UltimateDuel
api-version: '1.20'

commands:
  kit:
    description: Give an entire kit to any player.
    usage: /kit <gamemode> [targetplayer]

  heal:
    description: Heals a player.
    usage: /heal [targetplayer]

  lokadamage:
    description: Toggles 33% damage buff.
    usage: /lokadamage

  defaultsaturation:
    description: Sets default saturation on respawn and /heal.
    usage: /defaultsaturation <amount>